# Generated by Django 5.1.4 on 2025-03-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_registration_delete_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.AlterModelManagers(
            name='registration',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='username',
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
