# Generated by Django 5.1.4 on 2025-03-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0003_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
