# Generated by Django 5.1.4 on 2025-03-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0004_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='properties/main_images/')),
                ('sliding_images', models.FileField(blank=True, null=True, upload_to='properties/sliding_images/')),
            ],
        ),
    ]
